/* ============================================
   YISMAN Intimates - 依诗曼服装
   JavaScript
   ============================================ */

// ---- Language Data ----
const langData = {
  zh: {
    // Nav
    nav_home: '首页',
    nav_products: '产品中心',
    nav_factory: '工厂实力',
    nav_contact: '联系我们',
    nav_inquiry: '获取报价',

    // Hero
    badge: '🏭 工厂直供 · 品质保证',
    hero_title: '专注女士内衣<span em>制造</span>，<br>匠心每<em>一件</em>',
    hero_desc: '依诗曼服装 — 位于辽宁大连，拥有百人规模的现代化内衣工厂。15年行业经验，服务全球品牌客户，提供OEM/ODM一站式解决方案。',
    hero_btn1: '了解产品',
    hero_btn2: '工厂参观',

    // Stats
    stat1: '15+', stat1_label: '年行业经验',
    stat2: '200+', stat2_label: '员工人数',
    stat3: '500万+', stat3_label: '年产量(件)',
    stat4: '30+', stat4_label: '出口国家',

    // About
    about_title: '关于依诗曼',
    about_sub: '一家坐落于大连金州的现代化内衣制造企业',
    about_p1: '大连依诗曼服装有限公司成立于2010年，坐落于辽宁省大连市金州区。公司专注于女士内衣、文胸、内裤、塑身衣等产品的研发、生产和销售。',
    about_p2: '我们拥有先进的生产设备和完善的质量管理体系，月产能超过40万件。产品远销欧美、东南亚、中东等30多个国家和地区，与多家国际知名品牌建立了长期稳定的合作关系。',
    about_feat1: '15年行业经验',
    about_feat2: '百人专业团队',
    about_feat3: 'OEM/ODM定制',
    about_feat4: '严格质检体系',
    about_feat5: '快速打样7天',
    about_feat6: 'FOB大连出货',

    // Products
    pro_title: '产品中心',
    pro_sub: '品类齐全，满足不同市场需求',
    pro1_name: '无钢圈文胸',
    pro1_desc: '舒适无压迫，适合日常穿着。多色可选，支持定制logo和包装。',
    pro2_name: '蕾丝文胸',
    pro2_desc: '精致蕾丝面料，性感优雅。欧美版型设计，深受海外客户青睐。',
    pro3_name: '运动文胸',
    pro3_desc: '高弹透气面料，适中的支撑力。瑜伽、跑步、健身均适用。',
    pro4_name: '女士内裤',
    pro4_desc: '纯棉/莫代尔/蕾丝多种材质。平角、三角、丁字裤全品类。',
    pro5_name: '塑身衣',
    pro5_desc: '收腹提臀，强力塑形。进口面料，透气不闷热。',
    pro6_name: '睡衣/家居服',
    pro6_desc: '舒适柔软的家居系列。纯棉/丝质面料，简约时尚设计。',

    // Factory
    fac_title: '工厂实力',
    fac_sub: '先进设备 · 品质管控 · 产能保障',
    fac1_title: '现代化车间',
    fac1_desc: '3000㎡标准厂房，配备先进缝纫设备，车间恒温恒湿，确保生产环境稳定。',
    fac2_title: '专业质检体系',
    fac2_desc: '从面料入库到成品出库，每道工序严格把关。AQL2.5国际验货标准执行。',
    fac3_title: '快速打样',
    fac3_desc: '专业版房团队，收到设计稿后7-10天完成打样。支持来图来样定制。',
    fac4_title: '自有设计团队',
    fac4_desc: '经验丰富的设计师团队，每季推出新品。可根据客户需求进行定向研发。',
    fac5_title: '大货产能',
    fac5_desc: '月产能40万+件，能满足大订单需求。旺季产能可弹性调整至60万件/月。',
    fac6_title: '绿色环保',
    fac6_desc: '通过OEKO-TEX®认证，使用环保面料及染料。坚持可持续发展理念。',

    // Certs
    cert1: 'OEKO-TEX® 认证',
    cert2: 'BSCI 验厂报告',
    cert3: 'ISO 9001 质量体系',

    // Contact
    con_title: '联系我们',
    con_sub: '期待与您携手合作，共创美好未来',
    con_info_title: '联系方式',
    con_addr: '辽宁省大连市金州区[具体地址]',
    con_phone: '+86 180-4116-7816',
    con_email: '185436114@qq.com',
    con_whatsapp: 'WhatsApp / WeChat: +86 180-4116-7816',
    con_form_title: '发送询盘',
    con_form_name: '您的姓名',
    con_form_email: '邮箱地址',
    con_form_phone: '联系电话',
    con_form_country: '所在国家',
    con_form_msg: '询盘内容（产品要求/数量/等）',
    con_form_submit: '发送询盘',

    // Footer
    f_brand_desc: '专业女士内衣制造商，15年行业经验，为全球品牌提供OEM/ODM一站式服务。',
    f_quick: '快速链接',
    f_prod: '产品中心',
    f_about: '关于我们',
    f_factory: '工厂实力',
    f_contact: '联系我们',
    f_products_title: '产品系列',
    f_pro1: '无钢圈文胸',
    f_pro2: '蕾丝系列',
    f_pro3: '运动文胸',
    f_pro4: '女士内裤',
    f_contact_title: '联系方式',
    f_copy: '© 2026 大连依诗曼服装有限公司 版权所有',

    // Products page
    prod_header_title: '产品中心',
    prod_header_desc: '品类齐全，品质卓越，满足全球客户的多样化需求',
    prod_cta_text: '对产品感兴趣？立即联系我们获取详细目录和报价！',
    prod_cta_btn: '联系我们',

    // Factory page
    fac_header_title: '工厂实力',
    fac_header_desc: '先进生产设备，严谨品质管控，强大的产能保障',
    fac_video_title: '工厂实景',
    fac_video_desc: '欢迎莅临参观，眼见为实',
    fac_video_subtitle: 'YISMAN Factory Tour',

    // Contact page additional
    con_header_title: '联系我们',
    con_header_desc: '我们期待与您建立长期稳定的合作关系',
    con_working: '工作时间',
    con_working_time: '周一至周六 8:00 - 18:00（北京时间）',

    // ===== Workshop (ws_) =====
    ws_hero_title: '现代化车间',
    ws_hero_desc: '3000㎡标准化生产车间，配备日本JUKI、Brother等国际一线品牌缝纫设备，恒温恒湿环境控制，确保每一件产品都在最佳条件下生产。',
    ws_cta: '查看设备详情 →',
    ws_cta_title: '想要参观我们的车间？',
    ws_cta_desc: '欢迎莅临参观！我们随时为您安排工厂参观行程，亲眼见证我们的生产实力。',
    ws_cta_btn: '预约参观 →',
    ws_overview_title: '现代化车间概览',
    ws_overview_sub: 'Modern Workshop Overview',
    ws_desc_1: 'YISMAN拥有3000平方米的标准化生产车间，严格按照服装生产行业标准设计建造。车间布局科学合理，分为裁剪区、缝制区、整烫区、检验区和包装区五大功能区域，流水线作业高效顺畅。',
    ws_desc_2: '车间配备200余台日本JUKI和Brother品牌先进缝纫设备，包括电脑平缝机、包缝机、绷缝机、锁眼机、钉扣机等专业机型，可满足各种内衣产品的生产工艺需求。所有设备均按周期进行维护保养，确保稳定运行。',
    ws_desc_3: '车间采用中央空调系统，实现恒温恒湿控制——温度维持在24-26°C，湿度控制在55%-65%之间，为面料处理和缝制工艺提供最佳环境条件，有效减少因温湿度变化引起的面料收缩、变形等问题。',
    ws_stat1: '车间面积 (㎡)',
    ws_stat2: '缝纫设备 (台)',
    ws_stat3: '生产流水线 (条)',
    ws_stat4: '月产能 (件)',
    ws_stat5: '恒温控制',
    ws_stat6: '湿度控制',
    ws_equip_title: '主要设备清单',
    ws_equip_sub: 'Major Equipment List',
    ws_eq_no: '序号',
    ws_eq_name: '设备名称',
    ws_eq_brand: '品牌/型号',
    ws_eq_qty: '数量',
    ws_eq_use: '用途',
    ws_eq_use1: '一般缝纫，精密直线缝',
    ws_eq_use2: '布边包缝，弹性面料拼接',
    ws_eq_use3: '下摆、袖口绷缝，装饰线迹',
    ws_eq_use4: '自动锁眼，扣眼加工',
    ws_eq_use5: '自动钉扣，纽扣固定',
    ws_eq_use6: '蕾丝刺绣，花边装饰加工',
    ws_eq_use7: '自动裁剪面料，精准高效',
    ws_eq_use8: '蒸汽整烫，定型处理',
    ws_eq_use9: '面料检验，疵点检测',
    ws_eq_use10: '自动铺布，多层裁剪准备',
    ws_gallery_title: '车间实景展示',
    ws_gallery_sub: 'Workshop Gallery',
    ws_gall1: '全景生产线',
    ws_gall2: '车间实景',
    ws_gall3: '缝制区',
    ws_gall4: '工作区',
    ws_gall5: '生产区',
    ws_gall6: '工厂外景',
    ws_env_title: '车间环境标准',
    ws_env_sub: 'Workshop Environment Standards',
    ws_env1: '温度 24-26°C',
    ws_env2: '湿度 55-65%',
    ws_env3: '光照 500+ Lux',
    ws_env4: '无尘 10万级',
    ws_related_title: '其他工厂实力',
    ws_related_sub: 'More Factory Capabilities',

    // ===== Quality Control (qc_) =====
    qc_hero_title: '专业质检体系',
    qc_hero_desc: '从面料入库到成品出库，每道工序都经过严格的质量把控。我们严格执行AQL 2.5国际验货标准，拥有12+人的专业质检团队，确保每一件产品都达到客户期望的品质标准。',
    qc_cta: '查看质检流程 →',
    qc_cta_title: '品质是我们不变的承诺',
    qc_cta_desc: '对品质的执着让YISMAN成为值得信赖的内衣制造商。联系我们了解更多品控细节。',
    qc_cta_btn: '联系我们 →',
    qc_overview_title: '品质管控体系',
    qc_overview_sub: 'Quality Control System',
    qc_desc_1: 'YISMAN建立了完善的全流程品质管控体系，严格遵循AQL 2.5国际验货标准（正常检验水平II）。从面料入库到成品出库，我们设置了4道关键质量控制节点，确保问题早发现、早处理，不让一件不合格品流入下道工序。',
    qc_desc_2: '我们的质检团队由12+名经验丰富的QC人员组成，均经过系统培训和严格考核，熟练掌握各类内衣产品的检验标准和测试方法。团队包括面料检验员、过程巡检员、成品检验员和实验室测试员，各司其职、协同配合。',
    qc_desc_3: '质检中心配备先进的检测设备，涵盖面料物理性能测试、色牢度测试、尺寸稳定性测试、缝制强度测试等全方位检测能力。所有检测数据实时记录、可追溯。',
    qc_stat1: '质检阶段',
    qc_stat2: '专业质检员',
    qc_stat3: '出厂检验率',
    qc_stat4: '国际标准',
    qc_process_title: '四阶段质检流程',
    qc_process_sub: '4-Stage Quality Control Process',
    qc_step1_title: '面料入库检验 (Incoming QC)',
    qc_step1_desc: '每批面料到货后进行入库前检验：核查面料数量、规格、颜色与订单一致；检测面料色牢度、缩水率、克重、密度等物理指标；检查面料表面疵点、色差、异味等。不合格面料退回处理。',
    qc_step1_detail: '检验项目：色牢度测试、缩水率测试、克重检测、外观检验',
    qc_step2_title: '过程巡检 (In-Process QC)',
    qc_step2_desc: '生产过程中QC人员每小时对各工位进行巡检：检查半成品缝制质量，包括针距、线迹平整度、尺寸精度等；抽查裁剪、缝制、整烫各环节工艺执行情况；发现问题立即叫停整改，记录问题并追踪闭环。',
    qc_step2_detail: '巡检频率：每2小时/次，每批次抽检率≥30%',
    qc_step3_title: '成品检验 (Final Inspection)',
    qc_step3_desc: '成品完成后按AQL 2.5标准进行抽样检验：检查成品外观质量（线头、污渍、色差、对称度）；检查缝制质量（针距、线迹、起皱等）；试穿检验和尺寸复核；功能检测（扣子、拉链、松紧带等配件功能）。',
    qc_step3_detail: '检验标准：AQL 2.5 / Level II / Normal',
    qc_step4_title: '出货前检验 (Pre-Shipment QC)',
    qc_step4_desc: '包装完成后进行出货前最终检验：检查包装完整性和唛头信息准确性；按客户要求进行AQL抽检或100%全检；核对装箱数量、配码、颜色分配等；拍摄存档照片，出具检验报告。客户可委托第三方验货机构到场检验。',
    qc_step4_detail: '支持客户委托SGS、BV、Intertek等第三方验货',
    qc_equip_title: '检测设备清单',
    qc_equip_sub: 'Testing Equipment List',
    qc_eq_no: '序号',
    qc_eq_name: '设备名称',
    qc_eq_brand: '品牌/型号',
    qc_eq_test: '检测项目',
    qc_test1: '面料拉伸强度、缝线强度测试',
    qc_test2: '干/湿摩擦色牢度测试',
    qc_test3: '水洗色牢度、皂洗色牢度',
    qc_test4: '面料缩水率测试（5次家庭洗涤）',
    qc_test5: '面料耐磨性能测试',
    qc_test6: '耐汗渍色牢度测试',
    qc_test7: 'D65/TL84/UVA多光源对色',
    qc_test8: '断针及金属异物检测',
    qc_team_title: '专业质检团队',
    qc_team_sub: 'Professional QC Team',
    qc_team1: '总人数',
    qc_team2: '平均年限',
    qc_team3: '培训次数/年',
    qc_team4: '领班/组长',
    qc_team_desc: '我们的质检团队成员均经过ISO 9001质量管理体系培训，熟练掌握AQL抽样标准和各项检测操作规程。团队定期参加行业培训和考核，持续提升专业技能。我们承诺：所有出厂产品均经过严格检验，质量问题可追溯、可追责。',
    qc_related_title: '其他工厂实力',
    qc_related_sub: 'More Factory Capabilities',

    // ===== Sampling (sm_) =====
    sm_hero_title: '快速打样',
    sm_hero_desc: '专业版房团队，收到设计稿后7-10天即可完成打样。我们提供免费打样服务，支持来图来样定制。快速响应、精准还原，让您的设计想法第一时间变成实物。',
    sm_cta: '提交打样需求 →',
    sm_cta_title: '准备好了？开始您的打样之旅',
    sm_cta_desc: '将您的设计想法发给我们，7-10天即可收到实物样品。快速响应、精准还原。',
    sm_cta_btn: '立即咨询 →',
    sm_overview_title: '快速打样服务',
    sm_overview_sub: 'Fast Sampling Service',
    sm_desc_1: 'YISMAN拥有专业的板房团队，配备经验丰富的纸样师和样衣缝制师傅，能够快速精准地将设计图纸转化为实物样品。无论是客户提供设计图、参考图片还是实物样衣，我们都能准确理解和还原。',
    sm_desc_2: '常规打样周期为7-10个工作日（从收到设计资料确认后开始计算）。对于紧急项目，我们提供加急打样服务，最快3-5天即可出样。所有样品在寄出前均经过严格检查和试穿确认。',
    sm_desc_3: '我们针对有诚意的询盘提供免费打样服务，仅收取合理的样品邮寄费用。每位客户可享受2-3款免费打样名额，让您在合作前充分了解我们的工艺水平。',
    sm_stat1: '常规出样 (天)',
    sm_stat2: '加急出样 (天)',
    sm_stat3: '年打样数量',
    sm_stat4: '打样通过率',
    sm_process_title: '打样流程',
    sm_process_sub: 'Sampling Process',
    sm_step1_title: '设计稿接收 (Design Receipt)',
    sm_step1_desc: '客户提供设计图、效果图、参考图片或实物样衣。我们的技术团队审核设计的可生产性，确认面料辅料需求，评估生产工艺难度，给出优化建议。双方确认打样要求和时间节点。',
    sm_step1_detail: '客户需提供：设计图纸/参考图 + 尺寸表 + 面料要求',
    sm_step2_title: '纸样制作 (Pattern Making)',
    sm_step2_desc: '纸样师根据设计图和尺寸表进行纸样绘制，使用CAD软件进行放码和排料。对于内衣产品，特别注重曲线的精确度和各部位的比例协调。纸样完成后进行小样验证。',
    sm_step2_detail: '使用软件：Gerber AccuMark / Lectra Modaris',
    sm_step3_title: '样衣缝制 (Sample Sewing)',
    sm_step3_desc: '经验丰富的样衣工师按照纸样和工艺要求进行样衣缝制。选用指定面料和辅料，严格控制缝制工艺和细节处理。样衣完成后进行初步外观质量检查。',
    sm_step3_detail: '样衣工平均工龄：8年以上',
    sm_step4_title: '试穿调整 (Fitting & Adjustment)',
    sm_step4_desc: '样衣完成后进行真人试穿，评估穿着效果、舒适度和版型准确性。根据试穿结果进行必要的调整和修改，再次缝制完善。确保样衣在版型、做工、尺寸各方面都达到理想状态。',
    sm_step4_detail: '配备专业试穿模特，覆盖S/M/L/XL各尺码',
    sm_step5_title: '客户确认 (Customer Approval)',
    sm_step5_desc: '样衣完成后拍摄多角度照片和细节图发给客户确认。客户可以提出修改意见，我们免费提供1-2次修改调整。最终样衣经客户确认后，作为大货生产的标准参考。',
    sm_step5_detail: '确认后保留封样记录，大货严格按封样标准生产',
    sm_request_title: '提交打样需求',
    sm_request_sub: 'Submit Sampling Request',
    sm_request_info: '打样须知',
    sm_request_form: '填写打样需求',
    sm_info1: '免费打样：每位客户可免费打样2-3款',
    sm_info2: '修改免费：提供1-2次免费修改调整',
    sm_info3: '样品邮寄：客户承担实际运费，可到付',
    sm_info4: '支持格式：设计图(JPG/PDF/AI/CDR)、参考图、实物样衣',
    sm_info5: '保密承诺：客户设计资料严格保密，未经授权绝不外泄',
    sm_form_name: '您的姓名 *',
    sm_form_email: '邮箱 / WhatsApp *',
    sm_form_type: '产品类型 *',
    sm_form_type0: '请选择产品类型',
    sm_form_type1: '无钢圈文胸 / Wirefree Bra',
    sm_form_type2: '蕾丝文胸 / Lace Bra',
    sm_form_type3: '运动文胸 / Sports Bra',
    sm_form_type4: '女士内裤 / Panties',
    sm_form_type5: '其他 / Others',
    sm_form_quantity: '预计订购数量',
    sm_form_desc: '打样要求说明 *',
    sm_form_submit: '提交需求 →',
    sm_related_title: '其他工厂实力',
    sm_related_sub: 'More Factory Capabilities',

    // ===== Design Studio (ds_) =====
    ds_hero_title: '自有设计团队',
    ds_hero_desc: 'YISMAN拥有8人的专业设计团队，包括资深设计师、版型师和技术顾问。我们紧跟国际内衣潮流趋势，每季推出新款系列。同时可根据客户需求进行定向研发，提供OEM/ODM全套设计解决方案。',
    ds_cta: '了解设计服务 →',
    ds_cta_title: '让我们的设计师为您打造专属系列',
    ds_cta_desc: '从创意到成品，YISMAN设计团队全程为您服务。免费设计咨询，欢迎联系我们。',
    ds_cta_btn: '获取设计方案 →',
    ds_overview_title: '强大设计团队',
    ds_overview_sub: 'Professional Design Team',
    ds_desc_1: 'YISMAN的设计团队由8名经验丰富的专业人员组成，包括首席设计师、面料开发专员、版型设计师和技术工艺师。团队核心成员均拥有10年以上内衣行业设计经验，曾服务于多个国际知名品牌。',
    ds_desc_2: '我们采用CAD/CAM数字化设计系统（Gerber AccuMark、Lectra Modaris），实现从设计构思到纸样制作的全流程数字化。通过3D虚拟试衣技术，可以在打样前直观预览设计效果，大幅缩短开发周期。',
    ds_desc_3: '团队每季度前往欧洲、日韩参加国际内衣展会（如Paris Intim\'Expo、ISPO），追踪最新面料科技、色彩趋势和设计风格。结合国内市场特点和客户需求，开发兼具时尚感和实穿性的内衣产品。',
    ds_stat1: '设计师团队',
    ds_stat2: '平均经验 (年)',
    ds_stat3: '年均新款设计',
    ds_stat4: '合作品牌数量',
    ds_team_title: '团队成员',
    ds_team_sub: 'Meet Our Design Team',
    ds_member1: '20年内衣设计经验，曾任国际品牌设计总监，擅长蕾丝和时尚款设计',
    ds_member2: '15年打版经验，精通内衣结构设计，擅长无钢圈和塑身衣版型',
    ds_member3: '12年面料研发经验，熟悉功能性面料特性，负责新材料引进',
    ds_member4: '8年CAD制版经验，精通Gerber/ Lectra系统，负责数字化制版放码',
    ds_service_title: '设计服务流程',
    ds_service_sub: 'Design Service Process',
    ds_svc1_title: '需求沟通 (Requirement Brief)',
    ds_svc1_desc: '深入了解客户品牌定位、目标市场、目标客群和风格偏好。分析客户提供的参考图、竞品信息和产品要求。确定设计方向、品类结构和开发时间表。',
    ds_svc2_title: '创意设计 (Concept Design)',
    ds_svc2_desc: '设计师进行创意构思，绘制设计效果图和款式结构图。结合面料选择、色彩搭配和工艺细节，提供2-3个设计方向供客户选择。通过3D虚拟试衣展示设计效果。',
    ds_svc3_title: '技术实现 (Tech Development)',
    ds_svc3_desc: '设计确认后，版型师进行精确纸样制作和放码。工艺师编写生产工艺单，明确每道工序的操作要求和质量标准。CAD制版、排料优化，为后续打样和大货生产做好准备。',
    ds_svc4_title: '样衣跟进 (Sample Follow-up)',
    ds_svc4_desc: '设计师全程跟进打样过程，确保样品准确还原设计效果。试穿评估后进行调整优化，直至达到最佳效果。最终封样确认，为批量生产提供标准。',
    ds_portfolio_title: '设计案例',
    ds_portfolio_sub: 'Portfolio Examples',
    ds_port1_title: '蕾丝花边文胸系列',
    ds_port1_desc: '法式蕾丝与弹力网布拼接，性感优雅。含钢圈与无钢圈两种款式，覆盖A-D罩杯。',
    ds_port2_title: '运动文胸系列',
    ds_port2_desc: '高支撑性运动内衣，吸湿排汗面料，防震结构设计，适合中高强度运动。',
    ds_port3_title: '无痕内衣系列',
    ds_port3_desc: '一片式热压无缝工艺，隐形无痕设计，舒适贴合，适合贴身穿着和搭配紧身衣物。',
    ds_related_title: '其他工厂实力',
    ds_related_sub: 'More Factory Capabilities',

    // ===== Production (pr_) =====
    pr_hero_title: '大货产能',
    pr_hero_desc: 'YISMAN拥有强大的批量生产能力，月均产能40万+件，旺季峰值可达60万件。8条专业生产流水线，200+名熟练技术工人，产品远销全球30多个国家和地区，是值得信赖的大规模内衣制造商。',
    pr_cta: '查看生产周期 →',
    pr_cta_title: '准备下单生产？',
    pr_cta_desc: '无论订单大小，YISMAN都能为您提供稳定、高效的生产服务。获取报价，开始合作。',
    pr_cta_btn: '获取报价 →',
    pr_stats_title: '产能数据',
    pr_stats_sub: 'Production Capacity Data',
    pr_stat1: '月产能（件）',
    pr_stat2: '旺季峰值（件/月）',
    pr_stat3: '生产流水线（条）',
    pr_stat4: '熟练工人（人）',
    pr_stat5: '出口国家',
    pr_stat6: '年产量（件）',
    pr_stat7: '行业经验（年）',
    pr_stat8: '准时交付率',
    pr_timeline_title: '生产周期参考',
    pr_timeline_sub: 'Production Timeline by Order Size',
    pr_tl_qty: '订单数量',
    pr_tl_sampling: '打样周期',
    pr_tl_prod: '大货生产',
    pr_tl_total: '总周期',
    pr_tl_note: '说明',
    pr_tl_note1: '小批量试订单',
    pr_tl_note2: '常规订单量',
    pr_tl_note3: '推荐大批量',
    pr_tl_note4: '大批量订单',
    pr_tl_note5: '超大批量，需排期',
    pr_tl_footnote: '* 以上周期为常规参考，实际周期视产品复杂程度、面料交期等因素有所调整',
    pr_qa_title: '大货生产过程质量保障',
    pr_qa_sub: 'Quality Assurance During Mass Production',
    pr_qa1_title: '产前封样',
    pr_qa1_desc: '大货投产前，由确认样衣指导产前样制作，经品质部确认后方可批量生产，确保大货品质与样品一致。',
    pr_qa2_title: '首件检验',
    pr_qa2_desc: '每条生产线首批产品须经QC检验确认合格后，方可继续批量生产。首件不合格则查找原因并调整。',
    pr_qa3_title: '巡回质检',
    pr_qa3_desc: '生产过程中QC定时巡检各工位，抽检半成品质量。发现异常立即停线整改，问题闭环管理。',
    pr_qa4_title: '尾期抽检',
    pr_qa4_desc: '大货完成后按AQL 2.5标准进行随机抽检。支持客户或第三方验货机构到场检验。',
    pr_qa5_title: '包装检验',
    pr_qa5_desc: '包装前逐件检查外观质量、线头处理、配件牢固度等。包装后核对标签、数量和包装完好性。',
    pr_qa6_title: '出货前确认',
    pr_qa6_desc: '拍照存档、出具出货检验报告。所有质量记录可追溯，为客户提供完整的品质证明文件。',
    pr_export_title: '全球出口市场',
    pr_export_sub: 'Global Export Markets',
    pr_export1: '北美市场',
    pr_export2: '欧洲市场',
    pr_export3: '东亚市场',
    pr_export4: '大洋洲市场',
    pr_export5: '中东市场',
    pr_export6: '南美市场',
    pr_related_title: '其他工厂实力',
    pr_related_sub: 'More Factory Capabilities',

    // ===== Eco (eco_) =====
    eco_hero_title: '绿色环保',
    eco_hero_desc: 'YISMAN始终将可持续发展作为企业核心价值之一。我们通过OEKO-TEX® Standard 100认证，使用环保面料和染料，建立水循环处理系统，推行绿色包装方案。在保障产品质量的同时，最大程度降低对环境的影响。',
    eco_cta: '查看认证详情 →',
    eco_cta_title: '选择绿色，选择可持续发展',
    eco_cta_desc: '让您的产品更环保、更可持续。联系我们了解环保面料方案和绿色生产细节。',
    eco_cta_btn: '可持续咨询 →',
    eco_overview_title: '绿色制造理念',
    eco_overview_sub: 'Green Manufacturing Philosophy',
    eco_desc_1: 'YISMAN将可持续发展融入企业经营的每一个环节。从原材料采购到成品交付，我们慎重评估每一个环节对环境的影响，并持续改进生产工艺和管理方式，以实现更绿色、更负责任的生产模式。',
    eco_desc_2: '我们优先选用经过OEKO-TEX®认证的环保面料，包括有机棉、天丝™（Lyocell）、莫代尔（Modal）、再生涤纶（Recycled Polyester）等可持续发展材料。所有染料和助剂均符合欧盟REACH法规要求，不含对人体有害的化学物质。',
    eco_desc_3: '在生产过程中，我们通过优化工艺减少水电消耗，建立废水处理系统实现水资源循环利用。包装材料优先选用可降解、可回收的环保材料。我们坚信，绿色制造不仅是对环境的责任，更是企业长期竞争力的保障。',
    eco_stat1: '环保面料占比',
    eco_stat2: '水循环利用率',
    eco_stat3: '可再生包装',
    eco_stat4: '环保认证数',
    eco_cert_title: '资质认证',
    eco_cert_sub: 'Certifications & Standards',
    eco_cert1_desc: '国际权威纺织品有害物质检测认证，确保产品不含有害物质，对皮肤友好安全。我们的产品通过OEKO-TEX® Standard 100 Class I认证（婴幼儿最高等级）。',
    eco_cert2_title: 'Global Recycled Standard',
    eco_cert2_desc: '全球回收标准认证，验证再生材料含量和供应链追溯。我们使用经GRS认证的再生涤纶和再生尼龙面料。',
    eco_cert3_desc: '商业社会标准倡议认证，定期接受审计，确保工厂在社会责任、劳工权益、工作环境和环境保护方面符合国际标准。',
    eco_cert4_desc: '国际标准化组织质量管理体系认证，确保产品和服务从设计到交付全流程符合质量管理标准。',
    eco_cert5_title: 'ZDHC 零排放',
    eco_cert5_desc: 'Zero Discharge of Hazardous Chemicals，我们严格遵守有害化学品零排放承诺，所有废水经处理后达标排放。',
    eco_cert6_title: 'REACH 合规',
    eco_cert6_desc: '所有产品符合欧盟REACH法规要求，不使用SVHC高关注物质清单中的有害化学品，确保产品安全出口欧洲市场。',
    eco_practice_title: '可持续发展实践',
    eco_practice_sub: 'Sustainability Practices',
    eco_prac1_title: '环保材料应用',
    eco_prac1_desc: '85%以上的产品使用环保面料，包括GOTS认证有机棉、FSC认证天丝™、Lenzing Modal等。逐步淘汰传统涤纶，转用再生涤纶（rPET）替代，每年减少约20吨原生塑料消耗。',
    eco_prac2_title: '水资源管理',
    eco_prac2_desc: '投资建设日处理能力100吨的废水处理站，采用MBR膜生物反应工艺，处理后水质达到GB 4287-2012排放标准。水循环利用率达到60%，年节水量约18,000吨。',
    eco_prac3_title: '节能减排',
    eco_prac3_desc: '车间全面更换LED节能照明，安装智能电表实时监测能耗。采用变频电动缝纫机，比传统机型节能30%。蒸汽系统余热回收利用，每年减少碳排放约50吨。',
    eco_prac4_title: '绿色包装方案',
    eco_prac4_desc: '全面使用FSC认证再生纸板包装盒，取消塑料吊牌卡，改用再生纸卡。产品包装袋使用可降解PLA（聚乳酸）材料。为客户提供简化包装选项，全年减少塑料使用约5吨。',
    eco_prac5_title: '废弃物管理',
    eco_prac5_desc: '推行精益生产，通过优化排料和裁剪方案，面料利用率从78%提升至85%。边角料分类回收，与专业的再生资源公司合作进行纤维再生处理。危险废弃物（化学品容器等）交由资质单位处置。',
    eco_prac6_title: '社会责任',
    eco_prac6_desc: '通过BSCI验厂认证，保障员工合法权益。每月组织环保培训，提高全员环保意识。设立绿色生产奖励制度，鼓励员工提出环保改善建议。积极参与社区环保公益活动。',
    eco_related_title: '其他工厂实力',
    eco_related_sub: 'More Factory Capabilities',
  },

  en: {
    nav_home: 'Home',
    nav_products: 'Products',
    nav_factory: 'Factory',
    nav_contact: 'Contact',
    nav_inquiry: 'Get a Quote',

    badge: '🏭 Factory Direct · Quality Guaranteed',
    hero_title: 'Premium Women\'s <em>Intimates</em><br>Manufacturer in <em>China</em>',
    hero_desc: 'YISMAN Garments — Located in Dalian, Liaoning. A 100+ staff modern lingerie factory with 15 years of experience, serving global brands with OEM/ODM solutions.',
    hero_btn1: 'Our Products',
    hero_btn2: 'Factory Tour',

    stat1: '15+', stat1_label: 'Years Experience',
    stat2: '200+', stat2_label: 'Skilled Workers',
    stat3: '5M+', stat3_label: 'Annual Output',
    stat4: '30+', stat4_label: 'Export Countries',

    about_title: 'About YISMAN',
    about_sub: 'A modern lingerie manufacturer based in Jinzhou, Dalian',
    about_p1: 'YISMAN Garments Co., Ltd., established in 2010, is located in Jinzhou District, Dalian, Liaoning. We specialize in R&D, production and sales of women\'s underwear, bras, panties, shapewear and more.',
    about_p2: 'With advanced equipment and strict quality control, our monthly capacity exceeds 400,000 pieces. Our products are exported to Europe, Americas, Southeast Asia, Middle East and more, serving internationally renowned brands.',
    about_feat1: '15 Years Experience',
    about_feat2: '100+ Staff Team',
    about_feat3: 'OEM/ODM Service',
    about_feat4: 'Strict QC System',
    about_feat5: '7-Day Sampling',
    about_feat6: 'FOB Dalian Shipment',

    pro_title: 'Products',
    pro_sub: 'Complete product range to meet diverse market demands',
    pro1_name: 'Wirefree Bras',
    pro1_desc: 'Comfortable, pressure-free. Ideal for daily wear. Multiple colors, customizable logo & packaging.',
    pro2_name: 'Lace Bras',
    pro2_desc: 'Exquisite lace fabric, elegant & sexy. European/American sizing. Highly popular with overseas buyers.',
    pro3_name: 'Sports Bras',
    pro3_desc: 'High-stretch breathable fabric, medium support. Suitable for yoga, running & fitness.',
    pro4_name: 'Women\'s Panties',
    pro4_desc: 'Cotton/Modal/Lace options. Hipster, bikini, thong — full range available.',
    pro5_name: 'Shapewear',
    pro5_desc: 'Tummy control, butt lift. Imported fabric, breathable and comfortable.',
    pro6_name: 'Pajamas & Loungewear',
    pro6_desc: 'Soft and comfortable home collection. Cotton/silk fabrics, minimalist stylish design.',

    fac_title: 'Factory Strength',
    fac_sub: 'Advanced Equipment · Quality Control · Capacity Assurance',
    fac1_title: 'Modern Workshop',
    fac1_desc: '3,000㎡ standard workshop with advanced sewing equipment. Temperature & humidity controlled.',
    fac2_title: 'Quality Control',
    fac2_desc: 'Strict inspection at every step from fabric intake to finished goods. AQL 2.5 standard.',
    fac3_title: 'Fast Sampling',
    fac3_desc: 'Professional pattern room. 7-10 days for samples. Custom designs welcome.',
    fac4_title: 'Design Team',
    fac4_desc: 'Experienced in-house designers releasing new collections every season. Custom R&D available.',
    fac5_title: 'Mass Production',
    fac5_desc: '400K+ pieces monthly capacity. Flexible expansion to 600K pieces/month during peak season.',
    fac6_title: 'Eco-Friendly',
    fac6_desc: 'OEKO-TEX® certified. Sustainable materials and dyes. Committed to green manufacturing.',

    cert1: 'OEKO-TEX® Certified',
    cert2: 'BSCI Audited',
    cert3: 'ISO 9001 Certified',

    con_title: 'Contact Us',
    con_sub: 'We look forward to partnering with you',
    con_info_title: 'Contact Information',
    con_addr: 'Jinzhou District, Dalian, Liaoning, China',
    con_phone: '+86 180-4116-7816',
    con_email: '185436114@qq.com',
    con_whatsapp: 'WhatsApp / WeChat: +86 180-4116-7816',
    con_form_title: 'Send Inquiry',
    con_form_name: 'Your Name',
    con_form_email: 'Email Address',
    con_form_phone: 'Phone Number',
    con_form_country: 'Country',
    con_form_msg: 'Inquiry Details (product requirements, quantity, etc.)',
    con_form_submit: 'Send Inquiry',

    f_brand_desc: 'Professional women\'s intimates manufacturer with 15 years of experience. OEM/ODM one-stop service for global brands.',
    f_quick: 'Quick Links',
    f_prod: 'Products',
    f_about: 'About Us',
    f_factory: 'Factory',
    f_contact: 'Contact Us',
    f_products_title: 'Products',
    f_pro1: 'Wirefree Bras',
    f_pro2: 'Lace Collection',
    f_pro3: 'Sports Bras',
    f_pro4: 'Panties',
    f_contact_title: 'Contact',
    f_copy: '© 2026 Dalian YISMAN Garments Co., Ltd. All Rights Reserved',

    prod_header_title: 'Our Products',
    prod_header_desc: 'Complete product range with premium quality to meet global customer demands',
    prod_cta_text: 'Interested in our products? Contact us for catalog and quotation!',
    prod_cta_btn: 'Contact Us',

    fac_header_title: 'Factory Strength',
    fac_header_desc: 'Advanced equipment, rigorous quality control, strong production capacity',
    fac_video_title: 'Factory Tour',
    fac_video_desc: 'Visit us to see our facility in person',
    fac_video_subtitle: 'YISMAN Factory Tour',

    con_header_title: 'Contact Us',
    con_header_desc: 'We look forward to building a long-term partnership with you',
    con_working: 'Working Hours',
    con_working_time: 'Mon-Sat 8:00-18:00 (Beijing Time)',

    // ===== Workshop (ws_) =====
    ws_hero_title: 'Modern Workshop',
    ws_hero_desc: 'A 3,000㎡ standardized production workshop equipped with world-class JUKI, Brother and other leading sewing machines. Temperature and humidity controlled to ensure optimal production conditions for every product.',
    ws_cta: 'View Equipment Details →',
    ws_cta_title: 'Want to tour our workshop?',
    ws_cta_desc: 'You are welcome to visit! We can arrange a factory tour anytime so you can see our production capabilities firsthand.',
    ws_cta_btn: 'Book a Tour →',
    ws_overview_title: 'Workshop Overview',
    ws_overview_sub: 'Modern Workshop Overview',
    ws_desc_1: 'YISMAN operates a 3,000㎡ standardized production workshop built to garment industry standards. The layout is scientifically divided into five functional areas: cutting, sewing, ironing, inspection and packing, ensuring efficient workflow.',
    ws_desc_2: 'The workshop is equipped with 200+ advanced JUKI and Brother sewing machines, including computerized lockstitch, overlock, interlock, buttonhole and button-attaching machines — capable of handling all types of intimate apparel production. All machines are maintained on a regular schedule.',
    ws_desc_3: 'A central air conditioning system maintains constant temperature (24-26°C) and humidity (55-65%), providing the optimal environment for fabric handling and sewing, effectively reducing shrinkage and deformation caused by environmental changes.',
    ws_stat1: 'Workshop Area (㎡)',
    ws_stat2: 'Sewing Machines',
    ws_stat3: 'Production Lines',
    ws_stat4: 'Monthly Capacity (pcs)',
    ws_stat5: 'Temperature Control',
    ws_stat6: 'Humidity Control',
    ws_equip_title: 'Major Equipment List',
    ws_equip_sub: 'Major Equipment List',
    ws_eq_no: 'No.',
    ws_eq_name: 'Equipment Name',
    ws_eq_brand: 'Brand/Model',
    ws_eq_qty: 'Qty',
    ws_eq_use: 'Purpose',
    ws_eq_use1: 'General sewing, precision straight stitching',
    ws_eq_use2: 'Edge overlocking, elastic fabric joining',
    ws_eq_use3: 'Hem/cuff covering, decorative stitching',
    ws_eq_use4: 'Automatic buttonhole making',
    ws_eq_use5: 'Automatic button attaching',
    ws_eq_use6: 'Lace embroidery, decorative stitching',
    ws_eq_use7: 'Automatic fabric cutting, precise and efficient',
    ws_eq_use8: 'Steam ironing, setting treatment',
    ws_eq_use9: 'Fabric inspection, defect detection',
    ws_eq_use10: 'Automatic fabric spreading, multi-layer cutting prep',
    ws_gallery_title: 'Workshop Gallery',
    ws_gallery_sub: 'Workshop Gallery',
    ws_gall1: 'Full Production Line',
    ws_gall2: 'Workshop View',
    ws_gall3: 'Sewing Area',
    ws_gall4: 'Working Area',
    ws_gall5: 'Production Area',
    ws_gall6: 'Factory Exterior',
    ws_env_title: 'Workshop Environment Standards',
    ws_env_sub: 'Workshop Environment Standards',
    ws_env1: 'Temp 24-26°C',
    ws_env2: 'Humidity 55-65%',
    ws_env3: 'Lighting 500+ Lux',
    ws_env4: 'Dust-Free Class 100K',
    ws_related_title: 'More Factory Capabilities',
    ws_related_sub: 'More Factory Capabilities',

    // ===== Quality Control (qc_) =====
    qc_hero_title: 'Quality Control System',
    qc_hero_desc: 'From fabric intake to finished goods, every step undergoes strict quality checks. We strictly follow AQL 2.5 international standards with 12+ professional QC staff, ensuring every product meets customer quality expectations.',
    qc_cta: 'View QC Process →',
    qc_cta_title: 'Quality is Our Commitment',
    qc_cta_desc: 'Our dedication to quality makes YISMAN a trusted lingerie manufacturer. Contact us to learn more about our QC details.',
    qc_cta_btn: 'Contact Us →',
    qc_overview_title: 'Quality Control System',
    qc_overview_sub: 'Quality Control System',
    qc_desc_1: 'YISMAN has established a comprehensive full-process quality control system strictly following AQL 2.5 (Normal Inspection Level II). We set 4 key QC checkpoints from fabric intake to finished goods to detect and resolve issues early.',
    qc_desc_2: 'Our QC team consists of 12+ experienced professionals who have undergone systematic training and rigorous assessment. The team includes fabric inspectors, in-process inspectors, final inspectors and lab technicians working in coordination.',
    qc_desc_3: 'The QC center is equipped with advanced testing equipment covering fabric physical properties, color fastness, dimensional stability, seam strength and more. All test data is recorded in real-time and fully traceable.',
    qc_stat1: 'QC Stages',
    qc_stat2: 'QC Inspectors',
    qc_stat3: 'Inspection Rate',
    qc_stat4: 'Intl Standard',
    qc_process_title: '4-Stage QC Process',
    qc_process_sub: '4-Stage Quality Control Process',
    qc_step1_title: 'Incoming QC (Fabric Inspection)',
    qc_step1_desc: 'Every fabric batch is inspected upon arrival: verify quantity, specifications and color match orders; test color fastness, shrinkage, weight and density; check surface defects, color deviations and odors. Non-conforming fabrics are returned.',
    qc_step1_detail: 'Tests: Color fastness, shrinkage, weight, appearance inspection',
    qc_step2_title: 'In-Process QC',
    qc_step2_desc: 'QC inspectors patrol workstations every 2 hours during production: check semi-finished sewing quality including stitch density, seam finish and dimensional accuracy; spot-check cutting, sewing and ironing processes. Issues are stopped immediately for correction.',
    qc_step2_detail: 'Frequency: Every 2 hours, sampling rate ≥30% per batch',
    qc_step3_title: 'Final Inspection',
    qc_step3_desc: 'Finished products are sampled per AQL 2.5 standards: check appearance (loose threads, stains, color deviation, symmetry); check sewing quality (stitch, seam, puckering); fitting test and size verification; functional tests (buttons, zippers, elastics).',
    qc_step3_detail: 'Standard: AQL 2.5 / Level II / Normal',
    qc_step4_title: 'Pre-Shipment Inspection',
    qc_step4_desc: 'Final inspection after packing: check packaging integrity and marking accuracy; perform AQL sampling or 100% inspection per client requirements; verify carton quantities, size ratios and color assortment; photo documentation and inspection report issued.',
    qc_step4_detail: 'Clients may commission SGS, BV, Intertek or other 3rd-party inspection',
    qc_equip_title: 'Testing Equipment List',
    qc_equip_sub: 'Testing Equipment List',
    qc_eq_no: 'No.',
    qc_eq_name: 'Equipment Name',
    qc_eq_brand: 'Brand/Model',
    qc_eq_test: 'Test Item',
    qc_test1: 'Fabric tensile strength, seam strength testing',
    qc_test2: 'Dry/wet rubbing color fastness testing',
    qc_test3: 'Washing color fastness, soaping fastness',
    qc_test4: 'Fabric shrinkage test (5 home launderings)',
    qc_test5: 'Fabric abrasion resistance testing',
    qc_test6: 'Perspiration color fastness testing',
    qc_test7: 'D65/TL84/UVA multi-source color matching',
    qc_test8: 'Needle breakage & metal foreign object detection',
    qc_team_title: 'Professional QC Team',
    qc_team_sub: 'Professional QC Team',
    qc_team1: 'Total Staff',
    qc_team2: 'Avg Experience (yrs)',
    qc_team3: 'Training Sessions/Year',
    qc_team4: 'Supervisors/Leads',
    qc_team_desc: 'All QC team members are trained in ISO 9001 quality management systems and proficient in AQL sampling standards and testing procedures. The team undergoes regular industry training and assessments. We guarantee: every shipped product is strictly inspected.',
    qc_related_title: 'More Factory Capabilities',
    qc_related_sub: 'More Factory Capabilities',

    // ===== Sampling (sm_) =====
    sm_hero_title: 'Fast Sampling',
    sm_hero_desc: 'Our professional pattern room team completes samples in 7-10 days from design receipt. We offer free sampling service and support custom designs from sketches, reference images or physical samples. Fast response, accurate reproduction.',
    sm_cta: 'Submit Sampling Request →',
    sm_cta_title: 'Ready to start your sampling journey?',
    sm_cta_desc: 'Send us your design ideas and receive physical samples in 7-10 days. Fast response, accurate reproduction.',
    sm_cta_btn: 'Inquire Now →',
    sm_overview_title: 'Fast Sampling Service',
    sm_overview_sub: 'Fast Sampling Service',
    sm_desc_1: 'YISMAN has a professional pattern room with experienced pattern makers and sample sewers who can quickly and accurately transform design drawings into physical samples. We can work from design drawings, reference images or physical garments.',
    sm_desc_2: 'Standard sampling takes 7-10 working days (from design confirmation). For urgent projects, we offer expedited service with samples ready in 3-5 days. All samples are thoroughly checked and fit-tested before shipping.',
    sm_desc_3: 'We offer free sampling for serious inquiries. Clients only pay reasonable shipping costs. Each client is entitled to 2-3 free sample styles to evaluate our craftsmanship before placing orders.',
    sm_stat1: 'Standard (days)',
    sm_stat2: 'Expedited (days)',
    sm_stat3: 'Annual Samples',
    sm_stat4: 'Pass Rate',
    sm_process_title: 'Sampling Process',
    sm_process_sub: 'Sampling Process',
    sm_step1_title: 'Design Receipt',
    sm_step1_desc: 'Client provides design drawings, sketches, reference images or physical samples. Our technical team reviews producibility, confirms fabric/trim requirements, assesses production difficulty and provides optimization suggestions.',
    sm_step1_detail: 'Client provides: Design drawings/reference + size spec + fabric requirements',
    sm_step2_title: 'Pattern Making',
    sm_step2_desc: 'Pattern makers create patterns based on design drawings and size specs using CAD software for grading and nesting. Special attention is given to curve accuracy and proportion coordination for intimate apparel.',
    sm_step2_detail: 'Software: Gerber AccuMark / Lectra Modaris',
    sm_step3_title: 'Sample Sewing',
    sm_step3_desc: 'Experienced sample sewers stitch samples according to patterns and process requirements. Designated fabrics and trims are used with strict process control and detail handling. Initial appearance quality check after completion.',
    sm_step3_detail: 'Sample sewer average experience: 8+ years',
    sm_step4_title: 'Fitting & Adjustment',
    sm_step4_desc: 'Samples are fitted on live models to evaluate wearing effect, comfort and fit accuracy. Necessary adjustments are made based on fitting results. Ensuring the sample achieves ideal results in fit, workmanship and sizing.',
    sm_step4_detail: 'Professional fitting models available for S/M/L/XL sizes',
    sm_step5_title: 'Customer Approval',
    sm_step5_desc: 'Multi-angle photos and detail shots are sent to the client for approval. Clients may request modifications — we offer 1-2 free adjustments. The final approved sample serves as the standard reference for mass production.',
    sm_step5_detail: 'Sealed sample records kept; mass production strictly follows approved sample',
    sm_request_title: 'Submit Sampling Request',
    sm_request_sub: 'Submit Sampling Request',
    sm_request_info: 'Sampling Guidelines',
    sm_request_form: 'Sampling Request Form',
    sm_info1: 'Free sampling: 2-3 styles free per client',
    sm_info2: 'Free adjustments: 1-2 rounds of free modifications',
    sm_info3: 'Sample shipping: client pays actual freight, collect available',
    sm_info4: 'Accepted formats: Design drawings (JPG/PDF/AI/CDR), reference images, physical samples',
    sm_info5: 'Confidentiality: All client design materials are strictly confidential',
    sm_form_name: 'Your Name *',
    sm_form_email: 'Email / WhatsApp *',
    sm_form_type: 'Product Type *',
    sm_form_type0: 'Select product type',
    sm_form_type1: 'Wirefree Bra',
    sm_form_type2: 'Lace Bra',
    sm_form_type3: 'Sports Bra',
    sm_form_type4: 'Panties',
    sm_form_type5: 'Others',
    sm_form_quantity: 'Estimated Order Qty',
    sm_form_desc: 'Sampling Requirements *',
    sm_form_submit: 'Submit Request →',
    sm_related_title: 'More Factory Capabilities',
    sm_related_sub: 'More Factory Capabilities',

    // ===== Design Studio (ds_) =====
    ds_hero_title: 'Design Team',
    ds_hero_desc: 'YISMAN has an 8-member professional design team including senior designers, pattern makers and technical consultants. We track international lingerie trends and release new collections every season, while offering OEM/ODM design solutions.',
    ds_cta: 'Learn About Design Services →',
    ds_cta_title: 'Let our designers create your exclusive collection',
    ds_cta_desc: 'From concept to finished product, YISMAN\'s design team serves you every step of the way. Free design consultation — contact us today.',
    ds_cta_btn: 'Get Design Proposal →',
    ds_overview_title: 'Professional Design Team',
    ds_overview_sub: 'Professional Design Team',
    ds_desc_1: 'YISMAN\'s design team consists of 8 experienced professionals including a chief designer, fabric development specialist, pattern designer and process engineer. Core members have 10+ years of lingerie design experience.',
    ds_desc_2: 'We use CAD/CAM digital design systems (Gerber AccuMark, Lectra Modaris) for fully digital workflow from concept to pattern making. 3D virtual fitting technology allows visual preview before sampling, significantly reducing development cycles.',
    ds_desc_3: 'The team attends international lingerie exhibitions (Paris Intim\'Expo, ISPO) quarterly to track the latest fabric technology, color trends and design styles. Combined with market insight and client needs, we develop fashion-forward yet wearable intimate apparel.',
    ds_stat1: 'Design Team',
    ds_stat2: 'Avg Experience (yrs)',
    ds_stat3: 'New Designs/Year',
    ds_stat4: 'Brand Partners',
    ds_team_title: 'Meet Our Design Team',
    ds_team_sub: 'Meet Our Design Team',
    ds_member1: '20 yrs lingerie design exp., former design director at intl brand, specializes in lace and fashion designs',
    ds_member2: '15 yrs pattern making exp., expert in intimate apparel structure, specializes in wirefree and shapewear patterns',
    ds_member3: '12 yrs fabric R&D exp., knowledgeable in functional fabrics, responsible for new material sourcing',
    ds_member4: '8 yrs CAD pattern exp., proficient in Gerber/Lectra systems, handles digital pattern grading',
    ds_service_title: 'Design Service Process',
    ds_service_sub: 'Design Service Process',
    ds_svc1_title: 'Requirement Brief',
    ds_svc1_desc: 'In-depth understanding of client brand positioning, target market, audience and style preferences. Analyze reference images, competitor info and product requirements. Define design direction, category structure and development timeline.',
    ds_svc2_title: 'Concept Design',
    ds_svc2_desc: 'Designers create design sketches and style structure drawings. Combined with fabric selection, color matching and process details, provide 2-3 design directions for client selection. Present design through 3D virtual fitting.',
    ds_svc3_title: 'Tech Development',
    ds_svc3_desc: 'After design approval, pattern makers create precise patterns and grading. Process engineers write production spec sheets detailing operation requirements and quality standards. CAD pattern making and marker optimization for subsequent sampling.',
    ds_svc4_title: 'Sample Follow-up',
    ds_svc4_desc: 'Designers follow the entire sampling process to ensure accurate reproduction. Fitting evaluation followed by adjustments until optimal results are achieved. Final sealed sample serves as standard for mass production.',
    ds_portfolio_title: 'Portfolio Examples',
    ds_portfolio_sub: 'Portfolio Examples',
    ds_port1_title: 'Lace Trim Bra Collection',
    ds_port1_desc: 'French lace combined with stretch mesh, elegant and sexy. Available in underwired and wirefree styles, covering A-D cups.',
    ds_port2_title: 'Sports Bra Collection',
    ds_port2_desc: 'High-support sports bras with moisture-wicking fabric and shock-absorbing structure design, suitable for medium to high intensity exercise.',
    ds_port3_title: 'Seamless Underwear Collection',
    ds_port3_desc: 'One-piece heat-pressed seamless technology, invisible design, comfortable fit, ideal for wearing under tight clothing.',
    ds_related_title: 'More Factory Capabilities',
    ds_related_sub: 'More Factory Capabilities',

    // ===== Production (pr_) =====
    pr_hero_title: 'Mass Production',
    pr_hero_desc: 'YISMAN has strong mass production capabilities with a monthly capacity of 400K+ pieces, peaking at 600K during high season. 8 professional production lines, 200+ skilled workers, exporting to 30+ countries worldwide.',
    pr_cta: 'View Production Timeline →',
    pr_cta_title: 'Ready to place an order?',
    pr_cta_desc: 'Regardless of order size, YISMAN provides stable, efficient production services. Get a quote and start cooperating.',
    pr_cta_btn: 'Get a Quote →',
    pr_stats_title: 'Production Capacity',
    pr_stats_sub: 'Production Capacity Data',
    pr_stat1: 'Monthly Capacity (pcs)',
    pr_stat2: 'Peak Season (pcs/mo)',
    pr_stat3: 'Production Lines',
    pr_stat4: 'Skilled Workers',
    pr_stat5: 'Export Countries',
    pr_stat6: 'Annual Output (pcs)',
    pr_stat7: 'Industry Experience (yrs)',
    pr_stat8: 'On-Time Delivery Rate',
    pr_timeline_title: 'Production Timeline',
    pr_timeline_sub: 'Production Timeline by Order Size',
    pr_tl_qty: 'Order Qty',
    pr_tl_sampling: 'Sampling',
    pr_tl_prod: 'Production',
    pr_tl_total: 'Total',
    pr_tl_note: 'Notes',
    pr_tl_note1: 'Trial order',
    pr_tl_note2: 'Standard order',
    pr_tl_note3: 'Recommended volume',
    pr_tl_note4: 'Large volume order',
    pr_tl_note5: 'Very large, requires scheduling',
    pr_tl_footnote: '* Timelines are estimates; actual may vary based on product complexity, fabric lead time and other factors',
    pr_qa_title: 'Quality During Mass Production',
    pr_qa_sub: 'Quality Assurance During Mass Production',
    pr_qa1_title: 'Pre-Production Sealing',
    pr_qa1_desc: 'Before mass production begins, pre-production samples are made guided by approved samples. Bulk production only starts after QC department approval, ensuring quality consistency.',
    pr_qa2_title: 'First-Piece Inspection',
    pr_qa2_desc: 'The first product from each production line must pass QC inspection before bulk production continues. If first piece fails, root cause is identified and corrected.',
    pr_qa3_title: 'Patrol Inspection',
    pr_qa3_desc: 'QC inspectors patrol workstations regularly during production, spot-checking semi-finished quality. Anomalies trigger immediate line stoppage for correction with closed-loop issue management.',
    pr_qa4_title: 'Final Random Inspection',
    pr_qa4_desc: 'After completion, random sampling per AQL 2.5 standards. Clients or third-party inspection agencies are welcome to conduct on-site inspection.',
    pr_qa5_title: 'Packing Inspection',
    pr_qa5_desc: 'Before packing, each piece is checked for appearance, loose threads and accessory fastness. After packing, labels, quantities and packaging integrity are verified.',
    pr_qa6_title: 'Pre-Shipment Confirmation',
    pr_qa6_desc: 'Photo documentation and shipment inspection report issued. All quality records are traceable, providing clients with complete quality certification documents.',
    pr_export_title: 'Global Export Markets',
    pr_export_sub: 'Global Export Markets',
    pr_export1: 'North America',
    pr_export2: 'Europe',
    pr_export3: 'East Asia',
    pr_export4: 'Oceania',
    pr_export5: 'Middle East',
    pr_export6: 'South America',
    pr_related_title: 'More Factory Capabilities',
    pr_related_sub: 'More Factory Capabilities',

    // ===== Eco (eco_) =====
    eco_hero_title: 'Eco-Friendly',
    eco_hero_desc: 'YISMAN places sustainable development at the core of our values. We hold OEKO-TEX® Standard 100 certification, use eco-friendly fabrics and dyes, operate a water recycling system, and implement green packaging solutions.',
    eco_cta: 'View Certifications →',
    eco_cta_title: 'Choose Green, Choose Sustainability',
    eco_cta_desc: 'Make your products more eco-friendly and sustainable. Contact us to learn about eco-friendly fabric options and green production details.',
    eco_cta_btn: 'Sustainability Inquiry →',
    eco_overview_title: 'Green Manufacturing Philosophy',
    eco_overview_sub: 'Green Manufacturing Philosophy',
    eco_desc_1: 'YISMAN integrates sustainable development into every aspect of our operations. From raw material procurement to finished product delivery, we carefully evaluate environmental impact and continuously improve processes for greener, more responsible production.',
    eco_desc_2: 'We prioritize OEKO-TEX® certified eco-friendly fabrics including organic cotton, TENCEL™ Lyocell, Modal and Recycled Polyester. All dyes and auxiliaries comply with EU REACH regulations, free from harmful chemicals.',
    eco_desc_3: 'In production, we optimize processes to reduce water and electricity consumption. We operate a wastewater treatment system for water recycling. Packaging materials prioritize biodegradable and recyclable options.',
    eco_stat1: 'Eco-Fabric Ratio',
    eco_stat2: 'Water Recycle Rate',
    eco_stat3: 'Renewable Packaging',
    eco_stat4: 'Eco Certifications',
    eco_cert_title: 'Certifications & Standards',
    eco_cert_sub: 'Certifications & Standards',
    eco_cert1_desc: 'Internationally权威 textile harmful substance testing certification, ensuring products are free from harmful substances and skin-friendly. Our products meet OEKO-TEX® Standard 100 Class I (highest infant level).',
    eco_cert2_title: 'Global Recycled Standard',
    eco_cert2_desc: 'GRS certification verifies recycled material content and supply chain traceability. We use GRS-certified recycled polyester and nylon fabrics.',
    eco_cert3_desc: 'Business Social Compliance Initiative certification. Regular audits ensure our factory meets international standards in social responsibility, labor rights, working environment and environmental protection.',
    eco_cert4_desc: 'ISO 9001 quality management system certification, ensuring products and services meet quality standards from design to delivery.',
    eco_cert5_title: 'ZDHC Zero Discharge',
    eco_cert5_desc: 'Zero Discharge of Hazardous Chemicals. We strictly adhere to the commitment of zero discharge of hazardous chemicals; all wastewater is treated to compliance standards before discharge.',
    eco_cert6_title: 'REACH Compliant',
    eco_cert6_desc: 'All products comply with EU REACH regulations. We do not use SVHC-listed hazardous chemicals, ensuring safe export to European markets.',
    eco_practice_title: 'Sustainability Practices',
    eco_practice_sub: 'Sustainability Practices',
    eco_prac1_title: 'Eco-Friendly Materials',
    eco_prac1_desc: 'Over 85% of our products use eco-friendly fabrics including GOTS-certified organic cotton, FSC-certified TENCEL™ and Lenzing Modal. We are phasing out traditional polyester in favor of recycled polyester (rPET), reducing virgin plastic consumption by ~20 tons annually.',
    eco_prac2_title: 'Water Management',
    eco_prac2_desc: 'We invested in a 100-ton/day wastewater treatment plant using MBR membrane bioreactor technology. Treated water meets GB 4287-2012 discharge standards. Water recycling rate reaches 60%, saving approximately 18,000 tons of water annually.',
    eco_prac3_title: 'Energy Conservation',
    eco_prac3_desc: 'LED energy-saving lighting throughout the workshop with smart meters for real-time energy monitoring. Variable-frequency sewing machines save 30% energy compared to conventional models. Steam system waste heat recovery reduces carbon emissions by ~50 tons annually.',
    eco_prac4_title: 'Green Packaging',
    eco_prac4_desc: 'FSC-certified recycled cardboard packaging boxes. Eliminated plastic hang tags,改用 recycled paper cards. Product bags use biodegradable PLA (polylactic acid) material. Simplified packaging options available, reducing annual plastic usage by ~5 tons.',
    eco_prac5_title: 'Waste Management',
    eco_prac5_desc: 'Lean production through optimized nesting and cutting plans has improved fabric utilization from 78% to 85%. Scraps are sorted and recycled through partnerships with professional resource recovery companies. Hazardous waste is disposed of by licensed handlers.',
    eco_prac6_title: 'Social Responsibility',
    eco_prac6_desc: 'BSCI certified, ensuring employee rights and interests. Monthly environmental training to raise awareness. Green production reward system encouraging employee suggestions. Active participation in community environmental initiatives.',
    eco_related_title: 'More Factory Capabilities',
    eco_related_sub: 'More Factory Capabilities',
  },

  ja: {
    // Nav
    nav_home: 'ホーム',
    nav_products: '製品情報',
    nav_factory: '工場紹介',
    nav_contact: 'お問い合わせ',
    nav_inquiry: '見積もり依頼',

    // Hero
    badge: '🏭 工場直送 · 品質保証',
    hero_title: '女性用インナーウェアに特化した<br><em>製造</em>、<span em>確かな</span>技術で<em>一着一着</em>',
    hero_desc: 'YISMAN — 中国遼寧省大連に拠点を置く、近代的なインナーウェア工場です。100名以上の従業員を擁し、15年の経験を活かしてグローバルブランドのお客様にOEM/ODMワンストップソリューションを提供しています。',
    hero_btn1: '製品を見る',
    hero_btn2: '工場見学',

    // Stats
    stat1: '15+', stat1_label: '年の経験',
    stat2: '200+', stat2_label: '従業員数',
    stat3: '500万+', stat3_label: '年間生産量（着）',
    stat4: '30+', stat4_label: '輸出先国数',

    // About
    about_title: 'YISMANについて',
    about_sub: '大連金州に拠点を置く近代的なインナーウェアメーカー',
    about_p1: '大連YISMAN衣装有限公司は2010年に設立され、遼寧省大連市金州区に所在しています。女性用インナーウェア、ブラジャー、パンティー、シェイプウェアなどの研究開発、生産、販売を専門としています。',
    about_p2: '先進的な生産設備と完全な品質管理体制を備え、月産能力は40万着を超えます。製品は欧米、東南アジア、中東など30以上の国と地域に輸出され、多くの国際的に有名なブランドと長期的な協力関係を築いています。',
    about_feat1: '15年の業界経験',
    about_feat2: '100名以上の専門チーム',
    about_feat3: 'OEM/ODMカスタマイズ',
    about_feat4: '厳格な品質管理体制',
    about_feat5: '7日間の迅速サンプリング',
    about_feat6: 'FOB大連出荷',

    // Products
    pro_title: '製品情報',
    pro_sub: '豊富な品揃えで多様な市場ニーズに対応',
    pro1_name: 'ワイヤレスブラ',
    pro1_desc: '締め付けがなく快適で、日常使いに最適。多彩な色展開、ロゴやパッケージのカスタマイズに対応。',
    pro2_name: 'レースブラ',
    pro2_desc: '繊細なレース生地、セクシーでエレガント。欧米向けの型紙設計で、海外のお客様に大好評です。',
    pro3_name: 'スポーツブラ',
    pro3_desc: '高伸縮・通気性に優れた生地、適度なサポート力。ヨガ、ランニング、フィットネスに最適。',
    pro4_name: 'レディースパンティー',
    pro4_desc: 'コットン/モダール/レースなど多彩な素材。ショーツ、ビキニ、Tバックなど全種類をラインナップ。',
    pro5_name: 'シェイプウェア',
    pro5_desc: 'お腹引き締め、ヒップアップ。輸入生地を使用、通気性が良くムレにくい。',
    pro6_name: 'パジャマ＆ルームウェア',
    pro6_desc: '快適で柔らかなホームコレクション。コットン/シルク生地、シンプルでスタイリッシュなデザイン。',

    // Factory
    fac_title: '工場の強み',
    fac_sub: '先進設備 · 品質管理 · 生産能力の保証',
    fac1_title: '近代的ワークショップ',
    fac1_desc: '3,000㎡の標準工場。先進的なミシン設備を完備し、恒温恒湿で安定した生産環境を確保しています。',
    fac2_title: '専門的な品質管理体制',
    fac2_desc: '生地の入庫から完成品の出荷まで、全工程を厳格に管理。AQL2.5国際検査基準を実施しています。',
    fac3_title: '迅速なサンプリング',
    fac3_desc: '専門のパターンルームチームが、デザイン受領後7～10日でサンプルを完成。図面や実物見本によるカスタマイズに対応。',
    fac4_title: '自社デザインチーム',
    fac4_desc: '経験豊富なデザイナーチームが毎シーズン新作を発表。お客様のニーズに応じたカスタム設計も承ります。',
    fac5_title: '大量生産能力',
    fac5_desc: '月産40万着以上の能力。大口注文にも対応可能で、繁忙期は60万着/月まで弾力的に調整可能。',
    fac6_title: '環境への配慮',
    fac6_desc: 'OEKO-TEX®認証を取得。環境に優しい生地と染料を使用し、持続可能な発展を目指しています。',

    // Certs
    cert1: 'OEKO-TEX® 認証',
    cert2: 'BSCI 監査レポート',
    cert3: 'ISO 9001 品質システム',

    // Contact
    con_title: 'お問い合わせ',
    con_sub: 'お客様とのパートナーシップを心よりお待ちしております',
    con_info_title: '連絡先',
    con_addr: '中国遼寧省大連市金州区',
    con_phone: '+86 180-4116-7816',
    con_email: '185436114@qq.com',
    con_whatsapp: 'WhatsApp / WeChat: +86 180-4116-7816',
    con_form_title: 'お問い合わせフォーム',
    con_form_name: 'お名前',
    con_form_email: 'メールアドレス',
    con_form_phone: '電話番号',
    con_form_country: 'ご国籍',
    con_form_msg: 'お問い合わせ内容（製品要件・数量など）',
    con_form_submit: '送信',

    // Footer
    f_brand_desc: '女性用インナーウェアの専門メーカー、15年の業界経験でグローバルブランドにOEM/ODMワンストップサービスを提供しています。',
    f_quick: 'クイックリンク',
    f_prod: '製品情報',
    f_about: '会社概要',
    f_factory: '工場紹介',
    f_contact: 'お問い合わせ',
    f_products_title: '製品シリーズ',
    f_pro1: 'ワイヤレスブラ',
    f_pro2: 'レースコレクション',
    f_pro3: 'スポーツブラ',
    f_pro4: 'レディースパンティー',
    f_contact_title: '連絡先',
    f_copy: '© 2026 大連YISMAN衣装有限公司 All Rights Reserved',

    // Products page
    prod_header_title: '製品情報',
    prod_header_desc: '豊富な品揃えと卓越した品質で、グローバルなお客様の多様なニーズにお応えします',
    prod_cta_text: '製品にご興味がおありですか？今すぐお問い合わせいただき、詳細なカタログと見積もりを入手してください！',
    prod_cta_btn: 'お問い合わせ',

    // Factory page
    fac_header_title: '工場の強み',
    fac_header_desc: '先進的な生産設備、厳格な品質管理、強力な生産能力',
    fac_video_title: '工場見学',
    fac_video_desc: '実際にご来場いただき、お確かめください',
    fac_video_subtitle: 'YISMAN 工場見学',

    // Contact page additional
    con_header_title: 'お問い合わせ',
    con_header_desc: '長期的で安定したパートナーシップを築けることを楽しみにしております',
    con_working: '営業時間',
    con_working_time: '月曜～土曜 8:00～18:00（北京時間）',

    // ===== Workshop (ws_) =====
    ws_hero_title: '近代的ワークショップ',
    ws_hero_desc: '3,000㎡の標準化された生産ワークショップ。JUKI、Brotherなどの国際的一線ブランドのミシン設備を完備し、恒温恒湿の環境で、すべての製品を最適な条件下で生産します。',
    ws_cta: '設備詳細を見る →',
    ws_cta_title: 'ワークショップをご見学希望の方へ',
    ws_cta_desc: 'いつでも工場見学を承っております。実際の生産能力をぜひご自身の目でお確かめください。',
    ws_cta_btn: '見学予約 →',
    ws_overview_title: 'ワークショップ概要',
    ws_overview_sub: 'ワークショップ概要',
    ws_desc_1: 'YISMANは3,000平方メートルの標準化生産ワークショップを保有し、アパレル生産業界の基準に従って設計・建設されています。裁断エリア、縫製エリア、アイロンエリア、検査エリア、包装エリアの5つの機能エリアに分かれ、効率的な流れ作業を実現しています。',
    ws_desc_2: 'ワークショップには200台以上のJUKI、Brother製の先進的なミシン設備があり、コンピューターロックミシン、オーバーロックミシン、カバーステッチミシン、ボタンホールミシン、ボタンつけミシンなど、あらゆるインナーウェアの生産工程に対応しています。',
    ws_desc_3: '中央空調システムにより、温度24～26°C、湿度55～65％に常時管理。生地の取り扱いと縫製に最適な環境を提供し、温湿度変化による生地の収縮や変形を効果的に抑制します。',
    ws_stat1: 'ワークショップ面積（㎡）',
    ws_stat2: 'ミシン設備（台）',
    ws_stat3: '生産ライン（本）',
    ws_stat4: '月産能力（着）',
    ws_stat5: '温度管理',
    ws_stat6: '湿度管理',
    ws_equip_title: '主要設備一覧',
    ws_equip_sub: '主要設備一覧',
    ws_eq_no: '番号',
    ws_eq_name: '設備名称',
    ws_eq_brand: 'ブランド/型番',
    ws_eq_qty: '数量',
    ws_eq_use: '用途',
    ws_eq_use1: '一般縫製、精密直線縫い',
    ws_eq_use2: '端部オーバーロック、伸縮性生地の接合',
    ws_eq_use3: '裾・袖口のカバーステッチ、飾り縫い',
    ws_eq_use4: '自動ボタンホール加工',
    ws_eq_use5: '自動ボタンつけ',
    ws_eq_use6: 'レース刺繍、レース装飾加工',
    ws_eq_use7: '自動生地裁断、精密で高効率',
    ws_eq_use8: 'スチームアイロン、セット加工',
    ws_eq_use9: '生地検査、欠点検出',
    ws_eq_use10: '自動生地展延、多層裁断準備',
    ws_gallery_title: 'ワークショップ実景',
    ws_gallery_sub: 'ワークショップギャラリー',
    ws_gall1: '全景生産ライン',
    ws_gall2: 'ワークショップ内部',
    ws_gall3: '縫製エリア',
    ws_gall4: '作業エリア',
    ws_gall5: '生産エリア',
    ws_gall6: '工場外観',
    ws_env_title: 'ワークショップ環境基準',
    ws_env_sub: 'ワークショップ環境基準',
    ws_env1: '温度 24-26°C',
    ws_env2: '湿度 55-65%',
    ws_env3: '照度 500+ Lux',
    ws_env4: '無塵 10万級',
    ws_related_title: 'その他の工場の強み',
    ws_related_sub: 'その他の工場の強み',

    // ===== Quality Control (qc_) =====
    qc_hero_title: '専門的な品質管理体制',
    qc_hero_desc: '生地の入庫から完成品の出荷まで、すべての工程で厳格な品質管理を実施。AQL 2.5国際検査基準に従い、12名以上の専門QCチームが、すべての製品をお客様の期待する品質基準に仕上げます。',
    qc_cta: '品質管理プロセスを見る →',
    qc_cta_title: '品質は変わらぬお約束',
    qc_cta_desc: '品質へのこだわりがYISMANを信頼されるインナーウェアメーカーにしています。品質管理の詳細についてはお問い合わせください。',
    qc_cta_btn: 'お問い合わせ →',
    qc_overview_title: '品質管理システム',
    qc_overview_sub: '品質管理システム',
    qc_desc_1: 'YISMANは完全な全工程品質管理体制を構築し、AQL 2.5国際検査基準（通常検査水準II）を厳守しています。4つの重要な品質管理ポイントを設定し、問題の早期発見・早期対応を実現しています。',
    qc_desc_2: 'QCチームは12名以上の経験豊富な品質管理専門家で構成され、体系的なトレーニングと厳格な評価を経て、あらゆるインナーウェアの検査基準と試験方法に精通しています。',
    qc_desc_3: '品質管理センターには最先端の試験設備が完備されており、生地の物理特性試験、色堅牢度試験、寸法安定性試験、縫製強度試験など、あらゆる試験に対応。すべてのデータはリアルタイムで記録・追跡可能です。',
    qc_stat1: '品質管理段階',
    qc_stat2: '専門QC担当者',
    qc_stat3: '出荷検査率',
    qc_stat4: '国際基準',
    qc_process_title: '4段階品質管理プロセス',
    qc_process_sub: '4段階品質管理プロセス',
    qc_step1_title: '入庫時検査（受入QC）',
    qc_step1_desc: '各ロットの生地到着時に入庫前検査を実施：数量、仕様、色の一致を確認。色堅牢度、収縮率、目付、密度などの物理指標を試験。表面の欠点、色差、異臭などをチェック。不適合品は返品。',
    qc_step1_detail: '試験項目：色堅牢度試験、収縮率試験、目付試験、外観検査',
    qc_step2_title: '工程内検査（プロセスQC）',
    qc_step2_desc: '生産中、QC担当者が各工程を2時間ごとにパトロール検査。半製品の縫製品質（針目、縫い目の均一性、寸法精度など）を確認。問題発見時は即時ライン停止・是正。',
    qc_step2_detail: '頻度：2時間ごと、抜取率1ロットあたり30%以上',
    qc_step3_title: '最終検査（完成品検査）',
    qc_step3_desc: '完成品をAQL 2.5基準に従って抜取検査。外観品質（糸くず、汚れ、色差、対称性）・縫製品質（針目、縫い目、シワ）・試着検査・サイズ確認・機能試験（ボタン、ファスナー、ゴムなど）を実施。',
    qc_step3_detail: '検査基準：AQL 2.5 / Level II / Normal',
    qc_step4_title: '出荷前検査（出荷前QC）',
    qc_step4_desc: '包装完了後に出荷前最終検査。包装の完全性とマーキング情報の正確性を確認。顧客の要求に応じてAQL抜取または100%全数検査を実施。検収報告書を発行。',
    qc_step4_detail: 'SGS、BV、Intertekなど第三者検査機関による立会い検査に対応',
    qc_equip_title: '試験設備一覧',
    qc_equip_sub: '試験設備一覧',
    qc_eq_no: '番号',
    qc_eq_name: '設備名称',
    qc_eq_brand: 'ブランド/型番',
    qc_eq_test: '試験項目',
    qc_test1: '生地引張強度、縫製強度試験',
    qc_test2: '乾/湿摩擦色堅牢度試験',
    qc_test3: '洗濯色堅牢度、石鹸洗い堅牢度',
    qc_test4: '生地収縮率試験（家庭洗濯5回）',
    qc_test5: '生地耐磨耗性試験',
    qc_test6: '耐汗色堅牢度試験',
    qc_test7: 'D65/TL84/UVA多光源色合わせ',
    qc_test8: '断針・金属異物検出',
    qc_team_title: '専門QCチーム',
    qc_team_sub: '専門QCチーム',
    qc_team1: '総人数',
    qc_team2: '平均経験年数',
    qc_team3: '研修回数/年',
    qc_team4: 'リーダー/班長',
    qc_team_desc: 'QCチームメンバーは全員ISO 9001品質管理システムのトレーニングを受けており、AQL抜取基準と各種試験操作手順に精通しています。定期的な業界研修と評価を通じて専門スキルを継続的に向上させています。',
    qc_related_title: 'その他の工場の強み',
    qc_related_sub: 'その他の工場の強み',

    // ===== Sampling (sm_) =====
    sm_hero_title: '迅速なサンプリング',
    sm_hero_desc: '専門のパターンルームチームが、デザイン受領後7～10日でサンプルを完成。無料サンプリングサービスを提供し、図面や実物見本によるカスタマイズに対応いたします。',
    sm_cta: 'サンプリング依頼 →',
    sm_cta_title: '準備はできましたか？サンプリングを始めましょう',
    sm_cta_desc: 'デザイン案をお送りいただければ、7～10日で実物サンプルをお届けします。迅速かつ正確に再現いたします。',
    sm_cta_btn: '今すぐお問い合わせ →',
    sm_overview_title: '迅速サンプリングサービス',
    sm_overview_sub: '迅速サンプリングサービス',
    sm_desc_1: 'YISMANは専門のパターンルームチームを有し、経験豊富なパタンナーとサンプル縫製職人が、デザイン図面を迅速かつ正確に実物サンプルに変換します。',
    sm_desc_2: '標準サンプリング期間は7～10営業日（デザイン資料確認後から起算）。緊急案件の場合は最短3～5日での出荷も可能です。すべてのサンプルは厳格な検査と試着確認を経て発送されます。',
    sm_desc_3: '本気でのお問い合わせには無料サンプリングサービスを提供しております（送料のみご負担）。お客様1社につき2～3型の無料サンプリング枠をご用意しております。',
    sm_stat1: '標準サンプル（日）',
    sm_stat2: '緊急サンプル（日）',
    sm_stat3: '年間サンプル数',
    sm_stat4: 'サンプル合格率',
    sm_process_title: 'サンプリングプロセス',
    sm_process_sub: 'サンプリングプロセス',
    sm_step1_title: 'デザイン受領',
    sm_step1_desc: 'お客様からデザイン図、イメージ画像、実物見本などをご提供いただきます。技術チームが生産可能性を審査し、最適化提案を行います。',
    sm_step1_detail: 'お客様ご提供：デザイン図/参考画像 + サイズ表 + 生地要件',
    sm_step2_title: 'パターン作成',
    sm_step2_desc: 'パタンナーがデザイン図とサイズ表に基づいてパターンを作成し、CADソフトでグレーディングとネスティングを行います。',
    sm_step2_detail: '使用ソフト：Gerber AccuMark / Lectra Modaris',
    sm_step3_title: 'サンプル縫製',
    sm_step3_desc: '経験豊富なサンプル縫製職人がパターンと工程要件に従ってサンプルを縫製。厳格な工程管理と細部処理を徹底します。',
    sm_step3_detail: 'サンプル縫製職人の平均経験：8年以上',
    sm_step4_title: '試着調整',
    sm_step4_desc: 'サンプル完成後、実際のモデルによる試着を実施し、着用感、快適性、型紙の正確性を評価。必要に応じて調整・修正を行います。',
    sm_step4_detail: '専門試着モデルを完備、S/M/L/XLサイズ対応',
    sm_step5_title: 'お客様承認',
    sm_step5_desc: 'マルチアングル写真と詳細画像をお客様に送付し、承認を取得。お客様からの修正依頼には無料で1～2回対応。最終承認サンプルを大量生産の基準とします。',
    sm_step5_detail: '承認後は封サンプル記録を保管、大量生産は厳格に封サンプル基準に従う',
    sm_request_title: 'サンプリング依頼を送信',
    sm_request_sub: 'サンプリング依頼を送信',
    sm_request_info: 'サンプリング案内',
    sm_request_form: 'サンプリング依頼フォーム',
    sm_info1: '無料サンプリング：お客様1社につき2～3型無料',
    sm_info2: '無料修正：1～2回の無料調整対応',
    sm_info3: 'サンプル発送：お客様に実費送料をご負担いただきます（着払い可能）',
    sm_info4: '対応形式：デザイン図（JPG/PDF/AI/CDR）、参考画像、実物見本',
    sm_info5: '秘密厳守：お客様のデザイン資料は厳重に管理し、無断で外部に開示することはございません',
    sm_form_name: 'お名前 *',
    sm_form_email: 'メール / WhatsApp *',
    sm_form_type: '製品タイプ *',
    sm_form_type0: '製品タイプをお選びください',
    sm_form_type1: 'ワイヤレスブラ',
    sm_form_type2: 'レースブラ',
    sm_form_type3: 'スポーツブラ',
    sm_form_type4: 'パンティー',
    sm_form_type5: 'その他',
    sm_form_quantity: '予定注文数量',
    sm_form_desc: 'サンプリング要件 *',
    sm_form_submit: '依頼を送信 →',
    sm_related_title: 'その他の工場の強み',
    sm_related_sub: 'その他の工場の強み',

    // ===== Design Studio (ds_) =====
    ds_hero_title: '自社デザインチーム',
    ds_hero_desc: 'YISMANは8名の専門デザインチーム（シニアデザイナー、パタンナー、技術コンサルタント）を擁し、国際的なインナーウェアのトレンドを追跡しながら、OEM/ODMデザインソリューションを提供しています。',
    ds_cta: 'デザインサービスを知る →',
    ds_cta_title: 'デザイナーがあなただけのコレクションを創り上げます',
    ds_cta_desc: 'クリエイティブから完成品まで、YISMANのデザインチームが一貫してサポート。無料デザイン相談を承っております。',
    ds_cta_btn: 'デザイン提案を取得 →',
    ds_overview_title: '充実したデザインチーム',
    ds_overview_sub: '充実したデザインチーム',
    ds_desc_1: 'YISMANのデザインチームは8名の経験豊富な専門家で構成され、チーフデザイナー、生地開発スペシャリスト、パターンデザイナー、技術エンジニアが含まれます。コアメンバーは全員10年以上のインナーウェア業界経験を有しています。',
    ds_desc_2: 'CAD/CAMデジタル設計システム（Gerber AccuMark、Lectra Modaris）を採用し、設計構想からパターン作成までの全工程をデジタル化。3Dバーチャル試着技術により、サンプリング前にデザインを視覚的に確認でき、開発期間を大幅に短縮します。',
    ds_desc_3: 'チームは四半期ごとに欧州、日本、韓国の国際インナーウェア展示会（Paris Intim\'Expo、ISPOなど）に参加し、最新の生地技術、色彩トレンド、デザインスタイルを追跡しています。',
    ds_stat1: 'デザインチーム',
    ds_stat2: '平均経験（年）',
    ds_stat3: '年間新作デザイン数',
    ds_stat4: '協力ブランド数',
    ds_team_title: 'チームメンバー',
    ds_team_sub: 'チームメンバー',
    ds_member1: '20年のインナーウェアデザイン経験、元国際ブランドデザインディレクター、レースとファッション系デザインを得意とする',
    ds_member2: '15年のパターン作成経験、インナーウェア構造設計に精通、ワイヤレスとシェイプウェアの型紙を得意とする',
    ds_member3: '12年の生地研究開発経験、機能性素材に精通、新素材の導入を担当',
    ds_member4: '8年のCADパターン経験、Gerber/Lectraシステムに精通、デジタル型紙・グレーディングを担当',
    ds_service_title: 'デザインサービスプロセス',
    ds_service_sub: 'デザインサービスプロセス',
    ds_svc1_title: 'ニーズヒアリング',
    ds_svc1_desc: 'お客様のブランドポジショニング、ターゲット市場、顧客層、スタイル嗜好を深く理解。参考画像や競合情報を分析し、デザインの方向性と開発スケジュールを確定します。',
    ds_svc2_title: 'コンセプトデザイン',
    ds_svc2_desc: 'デザイナーがクリエイティブな構想を練り、デザイン画とスタイル構造図を作成。生地選定、色彩コーディネート、工程詳細を組み合わせ、2～3のデザイン方向性をご提案します。',
    ds_svc3_title: '技術開発',
    ds_svc3_desc: 'デザイン確定後、パタンナーが精密な型紙作成とグレーディングを実施。技術者が生産指示書を作成し、各工程の操作要件と品質基準を明確にします。',
    ds_svc4_title: 'サンプルフォローアップ',
    ds_svc4_desc: 'デザイナーがサンプリングプロセス全体をフォローし、サンプルがデザインを正確に再現していることを確認。試着評価後に調整・最適化を行い、最終的な封サンプルを確定します。',
    ds_portfolio_title: 'デザイン事例',
    ds_portfolio_sub: 'デザイン事例',
    ds_port1_title: 'レーストリムブラコレクション',
    ds_port1_desc: 'フレンチレースとストレッチメッシュの組み合わせがセクシーでエレガント。ワイヤー入りとワイヤレスの2タイプ、A～Dカップ対応。',
    ds_port2_title: 'スポーツブラコレクション',
    ds_port2_desc: 'ハイサポートのスポーツブラ。吸湿速乾素材と防振構造設計で、中～高強度の運動に最適。',
    ds_port3_title: 'シームレスインナーコレクション',
    ds_port3_desc: '一体型熱圧着シームレス技術。目に見えない設計で快適にフィットし、密着着用やタイトな服装の下に最適。',
    ds_related_title: 'その他の工場の強み',
    ds_related_sub: 'その他の工場の強み',

    // ===== Production (pr_) =====
    pr_hero_title: '大量生産',
    pr_hero_desc: 'YISMANは強力な大量生産能力を誇り、月間生産能力は40万着以上、繁忙期のピーク時には60万着に達します。8本の専門生産ライン、200名以上の熟練技能者を擁し、世界中の30以上の国と地域に製品を輸出しています。',
    pr_cta: '生産サイクルを見る →',
    pr_cta_title: 'ご注文をご検討中ですか？',
    pr_cta_desc: '注文規模を問わず、YISMANは安定した効率的な生産サービスを提供いたします。見積もりを取得して、協業を始めましょう。',
    pr_cta_btn: '見積もりを取得 →',
    pr_stats_title: '生産能力データ',
    pr_stats_sub: '生産能力データ',
    pr_stat1: '月産能力（着）',
    pr_stat2: '繁忙期ピーク（着/月）',
    pr_stat3: '生産ライン（本）',
    pr_stat4: '熟練技能者（名）',
    pr_stat5: '輸出先国数',
    pr_stat6: '年間生産量（着）',
    pr_stat7: '業界経験（年）',
    pr_stat8: '納期遵守率',
    pr_timeline_title: '生産サイクル目安',
    pr_timeline_sub: '注文規模別生産サイクル',
    pr_tl_qty: '注文数量',
    pr_tl_sampling: 'サンプリング',
    pr_tl_prod: '大量生産',
    pr_tl_total: '合計期間',
    pr_tl_note: '備考',
    pr_tl_note1: 'トライアル注文',
    pr_tl_note2: '標準注文',
    pr_tl_note3: '推奨量',
    pr_tl_note4: '大口注文',
    pr_tl_note5: '超大ロット、別途調整',
    pr_tl_footnote: '* 上記の期間は目安です。実際の期間は製品の複雑さや生地の納期などにより変動します',
    pr_qa_title: '大量生産時の品質保証',
    pr_qa_sub: '大量生産時の品質保証',
    pr_qa1_title: '生産前封サンプル',
    pr_qa1_desc: '大量生産開始前に、承認済みサンプルを基に生産前サンプルを作成。品質部門の承認を得てから量産を開始し、品質の一貫性を確保します。',
    pr_qa2_title: '初品検査',
    pr_qa2_desc: '各生産ラインの初回製品はQC検査に合格してから量産を継続。初品不合格の場合は原因を特定して修正します。',
    pr_qa3_title: '巡回品質検査',
    pr_qa3_desc: '生産中、QC担当者が定期的に各工程をパトロールし、半製品の品質を抜取検査。異常発見時は直ちにラインを停止し、クローズドループで管理します。',
    pr_qa4_title: '最終抜取検査',
    pr_qa4_desc: '完成品をAQL 2.5基準に従ってランダム抜取検査。お客様または第三者検査機関による立会い検査も承ります。',
    pr_qa5_title: '包装検査',
    pr_qa5_desc: '包装前に1着ずつ外観品質、糸処理、付属品の固定状態などを確認。包装後にラベル、数量、包装の完全性を検証します。',
    pr_qa6_title: '出荷前確認',
    pr_qa6_desc: '写真記録を保存し、出荷検査報告書を発行。すべての品質記録は追跡可能で、お客様に完全な品質証明書類を提供します。',
    pr_export_title: 'グローバル輸出市場',
    pr_export_sub: 'グローバル輸出市場',
    pr_export1: '北米市場',
    pr_export2: 'ヨーロッパ市場',
    pr_export3: '東アジア市場',
    pr_export4: 'オセアニア市場',
    pr_export5: '中東市場',
    pr_export6: '南米市場',
    pr_related_title: 'その他の工場の強み',
    pr_related_sub: 'その他の工場の強み',

    // ===== Eco (eco_) =====
    eco_hero_title: '環境への配慮',
    eco_hero_desc: 'YISMANは持続可能な発展を企業の中核的価値観の一つとして常に位置づけています。OEKO-TEX® Standard 100認証を取得し、環境に優しい生地と染料を使用、水循環処理システムを構築し、グリーンパッケージを推進しています。',
    eco_cta: '認証詳細を見る →',
    eco_cta_title: 'グリーンを選び、持続可能な発展を',
    eco_cta_desc: '環境に優しく、より持続可能な製品づくりを。環境配慮型の生地オプションとグリーン生産の詳細についてお問い合わせください。',
    eco_cta_btn: 'サステナビリティ相談 →',
    eco_overview_title: 'グリーン製造理念',
    eco_overview_sub: 'グリーン製造理念',
    eco_desc_1: 'YISMANは持続可能な発展を企業運営のあらゆる側面に組み込んでいます。原材料の調達から完成品の納品まで、環境への影響を慎重に評価し、よりグリーンで責任ある生産体制を追求しています。',
    eco_desc_2: 'OEKO-TEX®認証を受けた環境配慮型生地（オーガニックコットン、テンセル™、モダール、リサイクルポリエステルなど）を優先採用。すべての染料と助剤はEU REACH規則に準拠しています。',
    eco_desc_3: '生産工程では、工程最適化による水道光熱費の削減、排水処理システムの構築による水資源の循環利用を推進。包装材料は生分解性・リサイクル可能な環境配慮型素材を優先採用しています。',
    eco_stat1: '環境配慮型生地比率',
    eco_stat2: '水循環利用率',
    eco_stat3: '再生可能包装',
    eco_stat4: '環境認証数',
    eco_cert_title: '資格認証',
    eco_cert_sub: '資格認証',
    eco_cert1_desc: '国際的に権威のある繊維製品有害物質試験認証。製品に有害物質が含まれず、肌に優しく安全であることを保証します。OEKO-TEX® Standard 100 Class I（乳幼児最高等級）を取得。',
    eco_cert2_title: 'Global Recycled Standard',
    eco_cert2_desc: 'グローバルリサイクル基準認証。再生材料含有量とサプライチェーンのトレーサビリティを検証します。GRS認証を受けたリサイクルポリエステルとリサイクルナイロンを使用。',
    eco_cert3_desc: 'BSCI認証。定期的な監査を受け、社会的責任、労働者の権利、労働環境、環境保護に関する国際基準への適合を確認しています。',
    eco_cert4_desc: 'ISO 9001品質マネジメントシステム認証。設計から納品までの全プロセスが品質管理基準に適合していることを保証します。',
    eco_cert5_title: 'ZDHC ゼロエミッション',
    eco_cert5_desc: '有害化学物質のゼロ排出を厳守。すべての排水は処理後に基準を満たした状態で排出されます。',
    eco_cert6_title: 'REACH 準拠',
    eco_cert6_desc: 'すべての製品はEU REACH規則に準拠。SVHC高懸念物質リストの有害化学物質を使用せず、欧州市場への安全な輸出を確保しています。',
    eco_practice_title: 'サステナビリティへの取り組み',
    eco_practice_sub: 'サステナビリティへの取り組み',
    eco_prac1_title: '環境配慮型素材の活用',
    eco_prac1_desc: '85%以上の製品に環境配慮型生地を採用（GOTS認証オーガニックコットン、FSC認証テンセル™、Lenzingモダールなど）。従来のポリエステルからリサイクルポリエステル（rPET）への切り替えを進め、年間約20トンのバージンプラスチック消費を削減。',
    eco_prac2_title: '水資源管理',
    eco_prac2_desc: '日量100トンの処理能力を持つ排水処理施設を建設。MBR膜分離活性汚泥法を採用し、処理後の水質はGB 4287-2012排出基準に適合。水循環利用率は60%に達し、年間約18,000トンの節水を実現。',
    eco_prac3_title: '省エネ・排出削減',
    eco_prac3_desc: 'ワークショップ全体をLED省エネ照明に交換し、スマートメーターでリアルタイムにエネルギー消費を監視。インバータ制御電動ミシンの採用で従来機種比30%の省エネを達成。蒸気システムの余熱回収により年間約50トンのCO2削減。',
    eco_prac4_title: 'グリーンパッケージ',
    eco_prac4_desc: 'FSC認証再生紙箱を全面的に使用。プラスチックタグを廃止し再生紙カードに変更。製品包装袋は生分解性PLA（ポリ乳酸）素材を使用。簡略包装オプションも提供し、年間約5トンのプラスチック使用量を削減。',
    eco_prac5_title: '廃棄物管理',
    eco_prac5_desc: 'リーン生産を推進し、ネスティングと裁断計画の最適化により、生地利用率を78%から85%に向上。端材は分別回収し、専門の再生資源会社との協力で繊維再生処理を実施。',
    eco_prac6_title: '社会的責任',
    eco_prac6_desc: 'BSCI認証を取得し、従業員の正当な権利利益を保障。毎月環境研修を実施し、全従業員の環境意識を向上。グリーン生産奨励制度を設立し、従業員の環境改善提案を促進。地域の環境保護活動にも積極的に参加。',
    eco_related_title: 'その他の工場の強み',
    eco_related_sub: 'その他の工場の強み',
  }
};

// ---- Apply Language ----
function applyLang(lang) {
  document.documentElement.lang = lang;
  localStorage.setItem('yisman-lang', lang);

  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === lang);
  });

  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    if (langData[lang] && langData[lang][key]) {
      el.innerHTML = langData[lang][key];
    }
  });
}

// ---- Toggle Language ----
document.addEventListener('DOMContentLoaded', () => {
  // Load saved language or detect browser
  const saved = localStorage.getItem('yisman-lang');
  const detect = navigator.language || navigator.userLanguage;
  const defaultLang = saved || (detect && detect.startsWith('zh') ? 'zh' : 'en');
  applyLang(defaultLang);

  // Language buttons
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.addEventListener('click', () => applyLang(btn.dataset.lang));
  });

  // Hamburger menu
  const hamburger = document.querySelector('.hamburger');
  const navLinks = document.querySelector('.nav-links');
  if (hamburger) {
    hamburger.addEventListener('click', () => {
      navLinks.classList.toggle('open');
    });
  }

  // Close menu on link click
  document.querySelectorAll('.nav-links a').forEach(link => {
    link.addEventListener('click', () => {
      navLinks.classList.remove('open');
    });
  });

  // Back to top
  const backToTop = document.querySelector('.back-to-top');
  if (backToTop) {
    window.addEventListener('scroll', () => {
      backToTop.classList.toggle('show', window.scrollY > 400);
    });
    backToTop.addEventListener('click', () => {
      window.scrollTo({ top: 0, behavior: 'smooth' });
    });
  }

  // Active nav link
  const currentPage = window.location.pathname.split('/').pop() || 'index.html';
  document.querySelectorAll('.nav-links a').forEach(a => {
    const href = a.getAttribute('href');
    if (href === currentPage || (currentPage === '' && href === 'index.html')) {
      a.classList.add('active');
    }
  });

  // Stats counter animation
  const statNumbers = document.querySelectorAll('.stat-number');
  if (statNumbers.length > 0 && 'IntersectionObserver' in window) {
    let animated = false;
    const observer = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting && !animated) {
          animated = true;
          statNumbers.forEach(el => {
            const text = el.textContent;
            if (text.includes('+')) {
              const target = parseInt(text.replace(/[^0-9]/g, ''));
              let current = 0;
              const step = Math.ceil(target / 60);
              const interval = setInterval(() => {
                current += step;
                if (current >= target) {
                  current = target;
                  clearInterval(interval);
                }
                el.textContent = current + '+';
              }, 25);
            }
          });
          observer.disconnect();
        }
      });
    });
    statNumbers.forEach(el => observer.observe(el.parentElement));
  }
});
